### ISSUE TITLE
ETL Config DTO

### ISSUE THREAD

**Issue by grahamcrowell** [grahamcrowell/yafa#26]
- [ ] define pydantic class for `etl-config.yaml`
- [ ] replace usages of raw dict config

```yaml
# etl-config.yaml
# read by etl loader
delimiter: ","
num_workers: 4
chunk_size: 5000
worker_timeout: 10
mappings:
  symbol: 0
  date: 1
  open: 2
  high: 3
  low: 4
  close: 5
data_path: "raw_full_prices.csv"
```
